"use client";
import Sidebar from "@/components/layout/Sidebar";
import Header from "@/components/layout/Header";
import { useAlerts, useUi } from "@/lib/store";
import { Bell, ShieldAlert, CheckCircle, AlertTriangle } from "lucide-react";
import { useTranslations } from "next-intl";

export default function AlertsPage() {
  const { sidebarOpen } = useUi();
  const { alerts, acknowledgeAlert } = useAlerts();
  const t = useTranslations("alerts");

  const getAlertIcon = (type: string) => {
    switch (type) {
      case "crisis": return <ShieldAlert className="text-red-400" size={18} />;
      case "warning": return <AlertTriangle className="text-amber-400" size={18} />;
      default: return <Bell className="text-purple-400" size={18} />;
    }
  };

  return (
    <div className="min-h-screen bg-sx-void text-white flex">
      <Sidebar />
      <div 
        className="flex-1 flex flex-col min-w-0 transition-all duration-300"
        style={{ paddingLeft: sidebarOpen ? "240px" : "80px" }}
      >
        <Header />
        <main className="p-6 mt-16 max-w-3xl mx-auto w-full space-y-6">
          <div className="glass rounded-3xl p-6 border border-white/5 flex flex-col gap-6">
            <div>
              <h2 className="text-display font-extrabold text-xl text-white">{t("title")}</h2>
              <p className="text-xs text-zinc-500 mt-1">
                Historical alerts and warnings generated by passive biomarker drift detection.
              </p>
            </div>

            <div className="space-y-3">
              {alerts.length === 0 ? (
                <p className="text-xs text-zinc-500 py-6 text-center">{t("noAlerts")}</p>
              ) : (
                alerts.map((alert) => (
                  <div 
                    key={alert.id} 
                    className={`p-4 rounded-2xl border flex items-start gap-4 transition-all ${
                      alert.acknowledged 
                        ? "bg-white/5 border-white/5 text-zinc-400" 
                        : "bg-red-500/5 border-red-500/20 text-red-200"
                    }`}
                  >
                    <div className="p-2 bg-white/5 rounded-xl flex-shrink-0">
                      {getAlertIcon(alert.type)}
                    </div>
                    
                    <div className="flex-1 min-w-0">
                      <p className="text-xs font-semibold text-white">{alert.message}</p>
                      <p className="text-[10px] text-zinc-500 mt-1 font-mono">{alert.timestamp}</p>
                    </div>

                    {!alert.acknowledged && (
                      <button
                        onClick={() => acknowledgeAlert(alert.id)}
                        className="bg-red-500/20 hover:bg-red-500/40 text-red-300 px-3 py-1.5 rounded-xl text-[10px] font-semibold font-mono cursor-pointer transition-colors"
                      >
                        Acknowledge
                      </button>
                    )}
                  </div>
                ))
              )}
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}
